### PR TITLE
Add support for different button events

### PR DESCRIPTION
**Pull request by sumnerboy12**
This supercedes #12 and #13.

### CODE REVIEW

**Comment by sumnerboy12** [comment]
NOTE: this PR removes all code relating to OLED support as it was not possible with the standard Adafruit OLED libraries to get the code to fit on an Uno clone (EtherTEN).

@austinscreations is going to look into a custom OLED library (trimmed down version) to see if we can fit it back in, but for now the LSC running on an Uno won't support an OLED display.

**Comment by austinscreations** [comment]
this is the library I've started for OLED support. only works with i2c 128x64 OLED. 
https://github.com/austinscreations/diet_i2c_display

@sumnerboy12 wasn't able to get it to work on his screen but someone else has stated they plan to test once their parts arrive.

if it's still too large then we can look at combining the GFX and SSD1306 into one library and remove redundant functions, then look for other optimizations as needed for EtherTen support.

**Comment by sumnerboy12** [comment]
This PR includes significant memory optimisations, which were needed for the firmware to work on an Arduino Uno with 96 buttons all storing state needed to report the different button events. This was a collaborative effort with moin#1097 (Superhouse.TV discord user).

**Comment by austinscreations** [comment]
wanted to add a note. that moin (superhouse discord user) had found a text only library for SSD1306 LCD that uses way less space. I haven't taken the time to try the library myself yet 

SSD1306Ascii - https://github.com/greiman/SSD1306Ascii

**Comment by jonoxer** [comment]
I'm going to merge this now, but then I'll add the OLED code back in with a condition that prevents it being included if the target board is an UNO or equivalent. That will allow it to work on a Mega, but not cause problems on smaller boards.

I haven't tested this code but I trust Ben's judgement :-)

**Comment by sumnerboy12** [comment]
Hold fire on adding it back in @jonoxer - we are working on adding full OLED support for both the Uno and Mega

**Comment by jonoxer** [comment]
No worries, I'll leave it then :-) The current firmware is doing some very strange things on my LSC, to the extent that I wonder if I have a serious hardware problem. It intermittently fails to detect one or more of the MCPs, it detects random button presses, and the MCU resets after every second button press! Very strange.

**Comment by sumnerboy12** [comment]
@jonoxer with the help of the lads on discord we found a problem with the proto shield you sent me (with the I2C connector and watchdog module). VCC on the I2C connector was wired to IOREF, which is not connected on the EtherTEN - so it was floating.

This was causing all sorts of problems for me, until I jumpered IOREF -> 5V on the proto shield. Worth checking on yours?

**Comment by jonoxer** [comment]
Oops, sorry! I've been running with a Mega which has IOREF connected, so I didn't catch that problem.

**Pull request merged**
